name: SeedGames
main: me.libraryaddict.Hungergames.Hungergames
author: TechToolbox (@nkomarn)
version: Build ${version}
description: A custom fork of LibHungergames for The Seed! Compiled ${maven.build.timestamp}.
load: startup
depend: [ProtocolLib]
softdepend: [LibsDisguises, Vault, TerrainControl]